path: '/Users/mariajosealvarez/IdeaProjects/vonfreiren.github.io/_books'
url_goodreads: 'https://www.goodreads.com/review/list/136789999-javier-freire-alvarez?order=d&ref=nav_mybooks&shelf=read&sort=date_read'

